apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8083       # porta interna (o que o container expõe)
      targetPort: 8083 # porta do container
      nodePort: 30083  # porta externa (opcional, se quiser fixar)
