name: CD Payment Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Payment Service to K8s
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        shell: powershell
        run: Set-Content -Path kubeconfig -Value $env:KUBECONFIG_CONTENT -Encoding Ascii
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          KUBECONFIG: kubeconfig

      - name: Replace placeholders in payment-deployment.yaml
        shell: bash
        run: |
          sed -i "s|\${{ secrets.DOCKERHUB_USERNAME }}|${{ secrets.DOCKERHUB_USERNAME }}|g" k8s/payment/payment-deployment.yaml
          sed -i "s|\${{ github.sha }}|${{ github.sha }}|g" k8s/payment/payment-deployment.yaml
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
          KUBECONFIG: kubeconfig

      - name: Apply Kubernetes manifests
        shell: powershell
        run: kubectl apply -f k8s/payment/ --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Restart Payment Service Deployment
        shell: powershell
        run: kubectl rollout restart deployment payment-service
        env:
          KUBECONFIG: kubeconfig

      - name: Check Deployment rollout status
        shell: powershell
        run: kubectl rollout status deployment payment-service --timeout=180s
        continue-on-error: true
        env:
          KUBECONFIG: kubeconfig
