name: CD Payment Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Payment Service to K8s
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        shell: powershell
        run: Set-Content -Path kubeconfig -Value $env:KUBECONFIG_CONTENT -Encoding Ascii
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          KUBECONFIG: kubeconfig

      - name: Apply Kubernetes manifests
        shell: powershell
        run: kubectl apply -f k8s/sale/ --validate=false
        env:
          KUBECONFIG: kubeconfig

      - name: Restart Payment Service Deployment
        shell: powershell
        run: kubectl rollout restart deployment payment-service
        env:
          KUBECONFIG: kubeconfig

      - name: Check Deployment rollout status
        shell: powershell
        run: kubectl rollout status deployment payment-service --timeout=180s
        continue-on-error: true
        env:
          KUBECONFIG: kubeconfig
