name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test and Docker Push    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Executar testes e gerar cobertura
        run: ./gradlew clean test jacocoTestReport

      - name: Upload do relatório JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml

      - name: Buildar imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest .

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem para o DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
